講義一覧ページに必要なエンドポイントをopenapi.ymlに定義
NU-wiki-web/nu-wiki-frontend pull request #14
Opened 2023-03-10 19:19 UTC by yutteee

以下のようにエンドポイントを定義しました。
- /lecture
  全ての講義情報を取得
- /lecture/filter
  絞り込み検索
- /lecture/search
  フリーワード検索
![スクリーンショット 2023-03-11 4 16 09](https://user-images.githubusercontent.com/83484258/224406053-0a2730ff-b953-4936-8a3f-9e8f06de4c3f.png)

openapi.ymlはswagger edittorで動作確認済みです。
<img width="704" alt="スクリーンショット 2023-03-11 4 17 38" src="https://user-images.githubusercontent.com/83484258/224406311-8ca36320-c0a3-4592-aba5-c66048f25dc8.png">

2023-03-12 07:16 UTC, yutteee commented
絞り込み検索とフリーワード検索を一つにまとめました。

<img width="719" alt="スクリーンショット 2023-03-12 16 14 33" src="https://user-images.githubusercontent.com/83484258/224530071-aaac8a28-fcdd-4eea-bdbc-59f38dbe0b90.png">

2023-03-21 08:57 UTC, nac-39 commented
あと、一つ懸念点なんだけど、ページネーションってフロントでやる想定？
（つまり全データをフェッチしてからフロントで頑張る）
もしくは、エンドポイントでページネーションを指定できるようにする(`offset`(開始位置)と`limit`(データ数)を指定できるようにする？

2023-03-21 08:59 UTC, nac-39 requested changes

2023-03-21 08:59 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                    teacher_name: { type: string, example: "田中角栄" }
teacher_nameをキャメルケースにしてほしい

2023-03-21 08:59 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                    department_id: { type: number, example: 3 }
department_idもキャメルケースにして欲しい

2023-03-21 08:59 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                    teacher_name: { type: string, example: "田中角栄" }
teacher_nameをキャメルケースにして欲しい

2023-03-21 08:59 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                    department_id: { type: number, example: 3 }
department_idをキャメルケースにして欲しい

2023-03-21 08:59 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +          content:
データの総数を表すtotalというプロパティを付け足して欲しい

2023-03-21 09:07 UTC, yutteee commented on mock_server/api/openapi.yaml
> +          content:
okです

2023-03-21 09:08 UTC, yutteee commented on mock_server/api/openapi.yaml
> +    post:
bodyに入れれば楽に叩けるかって思ってpostにしたので、そこまで考えてなかった...補足ありがとう
このままpostでいきます

2023-03-21 09:16 UTC, yutteee commented
jsonはキャメルケースをつか使った方がいいのね...全く気にしていなかった...!
現状DBがスネークケースだったのでjsonもスネークケースにしたんですけど、バック側でキャメルケースに直してから送ってくれるって認識でokですか?

2023-03-21 09:21 UTC, yutteee commented
> あと、一つ懸念点なんだけど、ページネーションってフロントでやる想定？ （=全データをフェッチしてからフロントで頑張る） もしくは、エンドポイントでページネーションを指定できるようにする (=クエリで`offset`(開始位置)と`limit`(データ数)を指定できるようにする？)

ページネーションはフロントでやる想定でした！
一度全部のデータを取得してそこからフロントが頑張るという感じです。一度に通信するデータの量は大きくなるけれど、全てをレンダリングする訳ではない、データ量もそこまで大きい訳ではないという理由からパフォーマンスにさほど影響はないと

2023-03-21 09:23 UTC, yutteee commented
押し間違えでクローズしてしまいましたすみません....

2023-03-21 09:26 UTC, nac-39 commented
> > あと、一つ懸念点なんだけど、ページネーションってフロントでやる想定？ （=全データをフェッチしてからフロントで頑張る） もしくは、エンドポイントでページネーションを指定できるようにする (=クエリで`offset`(開始位置)と`limit`(データ数)を指定できるようにする？)
> 
> ページネーションはフロントでやる想定でした！ 一度全部のデータを取得してそこからフロントが頑張るという感じです。一度に通信するデータの量は大きくなるけれど、全てをレンダリングする訳ではない、データ量もそこまで大きい訳ではないという理由からパフォーマンスにさほど影響はないと

おっけーです！具体的に何件ぐらいだとパフォーマンスに影響がでるのかもわからないし、当初はフロントでページネーション頑張るでいきましょう

2023-03-21 15:29 UTC, yutteee commented
レビューもらった点を修正しました！
変更点
- スネークケースをキャメルケースに
- 配列で返ってくる奴らにtotalを追加

また、objectで返さないといけないのになぜかarrayになっていた点もあったのでそこも修正しています...
またまた、grade(学年)に関しては前回string(B1, B2とか)にするって話になったのでそれも修正しました

2023-03-22 02:03 UTC, nac-39 approved these changes
OKです！

2023-03-22 02:03 UTC, merged