:+1: ログイン、新規登録周りのエンドポイントを定義 #16
NU-wiki-web/nu-wiki-frontend pull request #17
Opened 2023-03-20 07:11 UTC by hirakuuuu

ログインと新規登録周りのエンドポイントを定義しました。

基本的には、この議事録に書いてあることを実装しています。
https://www.notion.so/8e88cb8f47f94461b342b53744cd6c45?pvs=4

- /login : ログイン
- /signup/mail : ワンタイムパスワードをメールで送る
- /signup/auth : ワンタイムパスワードで認証
- /signup/register : 本登録
<img width="565" alt="image" src="https://user-images.githubusercontent.com/83483542/226270065-a197f808-f41e-478a-a8a9-357d03d5a32e.png">

セッションIDやuuidについては、以下のページを参考に、cookieでやりとりするように書いてみました。
https://swagger.io/docs/specification/authentication/cookie-authentication/?sbsearch=login

2023-03-21 11:36 UTC, nac-39 requested changes

2023-03-21 11:36 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                  email: { type: string, example: "foo@a.mail.nagoya-u.ac.jp" }
ここもドメインを@s.thers.ac.jpにしてほしい

2023-03-21 11:36 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +                email: { type: string, example: "foo@a.mail.nagoya-u.ac.jp" }
ここもドメインを@s.thers.ac.jpにしてほしい

2023-03-21 11:36 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +      name: JSESSIONID
`JSESSIONID`の名前の意味って何かある…？あったら全然そのままでいいと思う
推測だから全然違ってたらごめんだけど、JSESSIONIDってNUCTから持ってきた…？
NUCTのCookieがなんでJSESSIONIDっていう名前になっているかっていうとJavaのTomcatっていうライブラリのデフォルトのCookieの名前がそれだかららしい。
今回のプロジェクトではTomcat使わないし普通にSESSIONIDでいいのではと思った。

2023-03-21 11:36 UTC, nac-39 commented on mock_server/api/openapi.yaml
> +      name: UUID
名前がUUIDじゃない方がいいような気がした。
UID, USERID, SIGNUPIDなど表すものがわかりやすい方がいいと思った。あと、他のuuidを値として使うものをCookieに含めることになったら区別が面倒だと思う。ここでのuuidをユーザーのidにしないんだったら、SIGNUPIDが推しかなあ…

2023-03-21 11:37 UTC, nac-39 commented
(メモ)
CookieAuthの説明
https://swagger.io/docs/specification/authentication/cookie-authentication/?sbsearch=cookieauth

2023-03-23 02:45 UTC, hirakuuuu commented on mock_server/api/openapi.yaml
> +      name: JSESSIONID
ドキュメントに`JSESSIONID`って書いてあったから、そう付けるものなのかと思っただけで、特に意味は無いから`SESSIONID`に変えときます～

2023-03-30 01:53 UTC, merged