講義一覧ページの実装
NU-wiki-web/nu-wiki-frontend pull request #19
Opened 2023-03-24 19:26 UTC by yutteee

講義一覧ページの実装をしました。

講義情報取得、講義検索のエンドポイントを叩いて表示することができるようになっています。
また、講義情報が多い場合はページネーションが有効になります。
![スクリーンショット 2023-03-25 4 22 59](https://user-images.githubusercontent.com/83484258/227620578-198dba1d-1872-4b42-a379-cae844cf8228.png)

備考
useAwaitを使いたかったですが、responseの形式がネストされたオブジェクトになっており、ref()からうまく取得できないという状況になりました。

2023-03-30 03:22 UTC, nac-39 requested changes
コメント多くて申し訳ない！！
変更お願いします！！

2023-03-30 03:22 UTC, nac-39 commented on components/ui/templates/LectureList.vue
> +const displayLectures = ref<LectureType[]>();
あと、
```javascript
const exampleLectures = Array.from({ length: 30 }, (_, i) => ({
  id: i,
  name: `講義${i}`,
  teacherName: `先生${i}`,
  grade: "B2",
  year: 2022,
  term: "春",
  departmentId: 1,
}));
```
とかで適当に講義を30個生成して試してみたんだけど、ページネーションできないっぽいのでみてみてほしいです

2023-03-30 03:22 UTC, nac-39 commented on components/ui/templates/Search.vue
> +</template>
丸投げで申し訳ないんだけど、template内の型チェックを怒られないようにしてほしい
Volarっていうプラグインを入れるとtemplateの型チェックしてくれる
https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin

2023-03-30 15:34 UTC, yutteee commented on components/ui/templates/LectureList.vue
> +const displayLectures = ref<LectureType[]>();
消しちゃいけないやつを消してしまっていました...
動作確認までしてくれてありがとう！

2023-03-30 15:37 UTC, yutteee commented on components/ui/templates/LectureList.vue
> +);
computedで試してみたら処理が一気に減ったのでよかったです！
(watchが明示的でわかりやすいから使いすぎてしまうの直さないとなぁ...)

2023-03-30 15:46 UTC, yutteee commented
レビューしてもらった点修正しました! 動作確認までしてくれてありがとう！
学びが多くてよかったです！

nullかundefinedか~についてですが、undefinedで実装する方向に変えました
vuetifyのドロップダウンがデフォルトでundefinedを返すのでnullに変換するのはめんどくさかったからです
openapiの型定義でundefined許容できなくね?ってなってたからnullを使ってたけど、何とかなったのでundefinedで行きます

備考：API設計のnullかundefinedかは結構議論されてるっぽい
https://future-architect.github.io/articles/20211028b/

2023-03-31 02:12 UTC, nac-39 approved these changes
大量に変更ありがとう！！！！
OKです〜！（動作確認してないけど…！）

2023-03-31 02:27 UTC, nac-39 commented
openapi.yamlのpathsが`/files/{file-id}`みたいにケバブケースになってるとaspidaの生成がうまくいかなかったので、`file-id`->`fileid`にしました

2023-03-31 02:28 UTC, merged