過去問アップロードページ
NU-wiki-web/nu-wiki-frontend pull request #31
Opened 2023-04-16 13:26 UTC by nac-39

アップロード画面です。
講義を検索して、検索結果が0件だったら講義を追加画面が出てくるようにしたいと思っています。
この辺はバックエンドができてから調整したいと思っています。

時間ある時にレビューもらえるとありがたいです

![ScreenShot 2023-04-16 21 52 17](https://user-images.githubusercontent.com/83295760/232312714-b25683eb-7ad9-4d7c-a9d6-7a8ddb0b0956.png)
![ScreenShot20230416222224](https://user-images.githubusercontent.com/83295760/232314350-16566910-5a85-4d41-9fd2-bd4f52189c1a.png)
![ScreenShot 2023-04-16 22 24 12](https://user-images.githubusercontent.com/83295760/232314428-b4e2d830-c299-422b-a158-35ba02c3f2e5.png)

2023-04-19 05:24 UTC, hirakuuuu requested changes
確認しました
動作に問題はなさそうだけど、CSSが一部効いてなかったので、その修正だけお願いします。

2023-04-19 05:24 UTC, hirakuuuu commented on components/pages/upload/index.vue
> +    <div class="text-lg font-bold text-primary">過去問ファイル</div>
ここのテキストの色の指定が上書きされてるっぽいから、`!text-primary`にした方がよさそう

2023-04-19 05:24 UTC, hirakuuuu commented on components/pages/upload/index.vue
> +    <div class="text-lg font-bold text-primary">講義情報</div>
ここも`!text-primary`で！

2023-04-19 05:25 UTC, hirakuuuu commented
あと一応確認なんだけど、講義を検索のボタンを押したときにエラーが出て、これも後々調整するっていう認識で良い？
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83483542/232970306-ea41609b-7f6b-4592-b853-0531fe838f69.png">

2023-04-30 05:51 UTC, nac-39 commented
> あと一応確認なんだけど、講義を検索のボタンを押したときにエラーが出て、これも後々調整するっていう認識で良い？ <img alt="image" width="960" src="https://user-images.githubusercontent.com/83483542/232970306-ea41609b-7f6b-4592-b853-0531fe838f69.png">

あってる！講義情報のAPIを叩いてその結果によって分岐したいから、あとで調整しようと思ってる

2023-04-30 05:57 UTC, merged